tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#FFF8F7",
        primary: "#AF101A",
        "on-primary": "#ffffff",
        "primary-container": "#D32F2F",
        "on-primary-container": "#FFDAD6",
        secondary: "#775652",
        "on-secondary": "#ffffff",
        "secondary-container": "#FFDAD6",
        "on-secondary-container": "#2D1512",
        tertiary: "#715B29",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#FDDFA6",
        "on-tertiary-container": "#261900",
        error: "#BA1A1A",
        "on-error": "#ffffff",
        background: "#FFF8F7",
        "on-background": "#231A19",
        "surface-variant": "#F5DDDA",
        "on-surface-variant": "#534341",
        outline: "#857371",
        "surface-container-low": "#FFF1EF",
        "surface-container": "#F9EBE9",
        "surface-container-high": "#F3E5E3",
        "surface-container-highest": "#EDE0DE",
        "surface-container-lowest": "#ffffff",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
